schema_version: 1

context:
  name: flet-cli
  version: "0.80.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/flet_cli-${{ version }}.tar.gz
  sha256: ad776fbfe2554895a5bed29859a344cf4c1b4c0f6e8d3fa3b27c09d212ce1bc4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - flet
    - watchdog >=4.0.0
    - packaging >=25.0
    - qrcode >=7.4.2
    - tomli >=1.1.0
    - cookiecutter >=2.6.0

tests:
  - python:
      imports:
        - flet_cli
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/flet-dev/flet/tree/main/sdk/python/packages/flet-cli
  summary: Flet CLI is a command-line interface tool for Flet, a framework for building interactive multi-platform applications using Python.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
