schema_version: 1

context:
  name: flet-cli
  version: "0.86.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/flet_cli-${{ version }}.tar.gz
  sha256: b2f7ff6b47269cba4f5d5eeac4d6179211df1bc897879ea4f7ae62c2c97b2ca8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - flet ==${{ version }}
    - watchdog >=4.0.0
    - packaging >=25.0
    - qrcode >=7.4.2
    - tomli >=1.1.0
    - cookiecutter >=2.6.0
    - chardet <6
    - binaryornot <0.5

tests:
  - python:
      imports:
        - flet_cli
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/flet-dev/flet/tree/main/sdk/python/packages/flet-cli
  summary: Flet CLI is a command-line interface tool for Flet, a framework for building interactive multi-platform applications using Python.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
